### ISSUE TITLE
Any plans to integrate with Spring Data and support Datastax DSE Graph?

### ISSUE THREAD

**Issue by zifnab87** [Syncleus/Ferma#17]
I am curious if it would be possible to have a Spring Data integration of all the Gremlin graph databases - something like: https://github.com/gjrwebber/spring-data-gremlin but using Tinkerpop 3+. I was expecting a less verbose annotation style without the need to create new classes (framed vertices/edges) like it is done with neo4j ogm: https://github.com/neo4j/neo4j-ogm. It would be nice if spring-data-gremlin is merged in spring projects like neo4j one: https://github.com/spring-projects/spring-data-neo4j

I am also curious if Datastax DSE Graph could be supported out of the box from Ferma.

Thanks!

**Comment by freemo** [comment]
No "plans" but I would be happy to merge any solutions in this regard. So it would be a welcome addition as well. Is tinkerpop able to suppore Datastax DSE graph directly?

**Comment by zifnab87** [comment]
at least for my project I am using pure gremlin syntax to query and do mutations. The problem is actually they way they implicitly decide when to commit a transaction. Using a single statement in their fluent  gremlin api it is a single transaction. Using their string based gremlin api you can have a multiple statement transaction. They haven't implemented the explicit tinkerpop methods for starting a transaction and committing/rollbacking. So this is the problem right now..

**Comment by freemo** [comment]
@zifnab87 Correct me if im wrong but that sounds like a limitation that Ferma could not actually get around. If it doesnt provide the means to do something Ferma can't do it either.

**Comment by zifnab87** [comment]
Yeah you are correct although their fluent api is work in progress so hopefully when they finish their transaction implementation they can be integrated

https://datastax-oss.atlassian.net/browse/JAVA-1250
https://datastax-oss.atlassian.net/browse/JAVA-1311

**Comment by freemo** [comment]
@zifnab87 Most likely once they complete their API someone (maybe me) will write a tinkerpop driver for it. At that point Ferma will work with it out of the box without needing any modifications to Ferma itself.

**Comment by mullekay** [comment]
Is there an implementation for DSE Graph? Or is anyone aware of a JPA implementation for DSE Graph?
