### ISSUE TITLE
Adding a custom Annotation

### ISSUE THREAD

**Issue by mikrobe** [Syncleus/Ferma#22]
In order to register a custom Annotation, it is necessary to create an annotation method handler and add it to the AnnotationFrameFactory's methodHandlers map.
The issue is that AnnotationFrameFactory's methodHandlers is private, hence it is not accessible.
Changing it to "protected" it allows to extend AnnotationFrameFactory and add the custom annotation handler right inside the constructor.

**Comment by freemo** [comment]
@mikrobe hi, sorry I just noticed this ticket. Very sorry it slipped through the cracks, I usually implement issues quickly. I will investigate this and should have a fix in the next release for you.
