### ISSUE TITLE
Update Ferma to use Tinkerpop v3

### ISSUE THREAD

**Issue by freemo** [Syncleus/Ferma#3]
We need to start preparing Ferma to use Tinkerpop v3 as the backend. If we can get someone to update the code in a new branch to be fully compatible with the Tinkerpop v3 release, and all the unit tests passing we should be golden!

**Comment by ykim** [comment]
Any updates on this front? I'd be interested in helping, but I'm not too familiar with the differences between TP2 and TP3.

**Comment by freemo** [comment]
No takers yet. I am however going to put a few hundred dollars up as a
bounty on this feature if you're interested.

**Comment by Jotschi** [comment]
I quickly looked at the expected changes. Wrapping of graphs works differently in TP3. Predicate handling for traversals has changed. Vertices and Edges are now also directly traversals. So far i think much of the ferma codebase must be rewritten from scratch (com.syncleus.ferma.pipes, com.syncleus.ferma.traversals). It might be possible to utilize the TraversalStrategy feature in order to integrate Ferma with TP3.

**Comment by freemo** [comment]
Yea Ferma to support TP3 would likely be a considerable rewrite. Backwards
compatibility probably wouldn't exist. The main reason I myself haven't put
in the effort is because even if I wrote a Ferma for TP3 that worked
perfectly I wouldn't use it. TP3 is insanely poor in the performance
department, TP2 still blows it out of the water in that regard. I wrote
Ferma to replace Frames specifically to achieve better performance in the
applications I needed it for. So until TP3 comes "up to speed" (forgive the
pun) it isnt a high priority for me.

With that said I am willing to pay someone a few hundred dollars if they
wish to undertake a TP3 version of Ferma for the sake of others who may
wish to use TP3.

**Comment by freemo** [comment]
This issue now has a $150 bounty for anyone who can complete it.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=22479023)](https://www.bountysource.com/issues/22479023-update-ferma-to-use-tinkerpop-v3?utm_source=22479023&utm_medium=shield&utm_campaign=ISSUE_BADGE)
