### ISSUE TITLE
getVertex(id,class) method not implemented in DelegatingFramedGraph class

### ISSUE THREAD

**Issue by mohataher** [Syncleus/Ferma#4]
When converting from Frames to Ferma, I found this issue. 

Why `DelegatingFramedGraph` doesn't implement `getVertex(Object id, Class Type)`?

**Comment by freemo** [comment]
@mohataher  Please submit all issues via JIRA at http://bugs.syncleus.com .. Issues are only enabled on github for use with bountysource.
