### ISSUE TITLE
AdjacencyMethodHandler: IllegalStateException on Direction.OUT

### ISSUE THREAD

**Issue by enRGi** [Syncleus/Ferma#8]
Hi,

just wanted to take a quick look into Ferma and discovered the first issue. In AdjacencyMethodHandler.java, line 411 and 441 there is no 'break' so when using Direction.OUT an IllegalStateException is always thrown.

Best regards,
René

**Comment by freemo** [comment]
We use jira for our bug reporting, not github. But thanks for the report I'll fix it today. In the future please use: http://bugs.syncleus.com

**Comment by freemo** [comment]
Also since you are comparing Ferma and trying out the alternatives check this page out:
http://wiki.syncleus.com/index.php/Ferma:Comparing_the_Alternatives

**Comment by freemo** [comment]
@enRGi This fix has been merged into master and should now be working. it is part of 2.1.0 snapshot and will be released in the next released (which is likely to be later today). Thanks for your help.

**Comment by freemo** [comment]
@enRGi FYI version 2.1.0 has now been released with this fix incorporated.

**Comment by enRGi** [comment]
Thank you for your efforts and infos. I will look into it.
